### ISSUE TITLE
group layers

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2020-b-qgis-gtfs-plugin#12]
How?

* required/optional

**Comment by landam** [comment]
@AlzbetaGardonova Please suggest groups/subgroups structure.

**Comment by landam** [comment]
See https://github.com/ctu-geoforall-lab/qgis-ruian-plugin/blob/master/MainApp.py#L482

**Comment by AlzbetaGardonova** [comment]
Group structure:

gtfs_import (main group)
- trips
- transfers
- stops
- routes
- lines

   transfer (sub-group)
    - levels
    - pathways

   time management (sub-group)
    - stop_times
    - calendar
    - calendar_dates

   service info (sub-group)
    - agency
    - feed_info
    - route_sub_agencies
    - fare rules
    - fare attributes

**Comment by jardaGIS** [comment]
@AlzbetaGardonova @landam 
There can be also frequencies, translations and attributions csv file in GPKG format. In which group should these files be added? 
In your list there is no shapes layer. Should it be in main group?

**Comment by AlzbetaGardonova** [comment]
@jardaGIS  My mistake - lines used instead of shapes. fequencies ->time management, attributions ->service info, translations ->service info

**Comment by landam** [comment]
Change `gtfs_import` to `GTFS import (PID_GTFS.zip)`
