### ISSUE TITLE
set default styles

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2020-b-qgis-gtfs-plugin#13]
To be defined.

**Comment by AlzbetaGardonova** [comment]
color definition - table routes, column route_color (hex color without #)
routes join to trips and shapes, keys (route_id, shape_id)

or use added qml style

**Comment by landam** [comment]
> color definition - table routes, column route_color (hex color without #)
> routes join to trips and shapes, keys (route_id, shape_id)

yes, see https://github.com/ctu-fgis/2020-b-qgis-gtfs-plugin/blob/styles/GTFS.py#L365
